pipeline {
    agent any
    environment {
        AWS_CREDS = credentials('AWS_CREDS')
    }
    parameters {
        booleanParam(name: 'TF_INIT', defaultValue: false, description: 'Run terraform init')

        booleanParam(name: 'TF_IMPORT', defaultValue: false, description: 'Run terraform import')
        string(name: 'SECURITY_GROUP_ID', defaultValue: 'sg-0fa56eb26a8b66557', description: 'Security Group ID')

        booleanParam(name: 'TF_PLAN', defaultValue: false, description: 'Run terraform plan')
        
        booleanParam(name: 'TF_APPLY', defaultValue: false, description: 'Run terraform apply')        choice(name: 'TF_ACTION', choices: ['none', 'create', 'update'], description: 'Select the Terraform action')

        booleanParam(name: 'TF_DESTROY', defaultValue: false, description: 'Run terraform destroy')
    }
    stages {
        stage('Prerequisite') {
            steps {
                sh '''
                echo "==== Cleaning and Cloning Repo ===="
                rm -rf /var/lib/jenkins/workspace/security_group_crud/*
                git clone https://github.com/priyanshusaineni/aws_security_group_terraform.git
                '''
            }
        }
        stage('Terraform Init') {
            when {
                expression { params.TF_INIT }
            }
            steps {
                sh '''
                cd aws_security_group_terraform
                terraform init
                '''
            }
        }
        stage('Terraform Import') {
            when {
              expression { params.TF_IMPORT }
            }
            steps {
                  sh '''
                  cd aws_security_group_terraform
                  terraform import resource.aws_security_group.this ${SECURITY_GROUP_ID}
                  '''
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.TF_PLAN }
            }
            steps {
                sh '''
                cd aws_security_group_terraform
                terraform plan
                '''
            }
        }
        
        stage('Terraform Apply') {
            when {
                expression { params.TF_APPLY }
            }
            steps {
                  sh '''
                    cd aws_security_group_terraform
                    terraform apply --auto-approve
                  '''
            }
        }

        stage('Terraform Destroy') {
          when {
            expression { params.TF_DESTROY }
          }
          steps {
              sh """
                cd aws_security_group_terraform
                terraform destroy --auto-approve
              """
            }
          }
        }
    }
}